### ISSUE TITLE
ZooKeeperDistributedTree#create fails sometimes

### ISSUE THREAD

**Issue by hsestupin** [puniverse/galaxy#30]
Method `create(String node, boolean ephemeral)` is not thread safe. Pattern 

    if (exists(path)) {
      return;
    }
    createNode(path);

doesn't work in distributed environment. To make this pattern thread-safe we have to catch and ignore `KeeperException$NodeExistsException` while creating a node.

**Comment by hsestupin** [comment]
I could submit a PR in a few days if you dont mind

**Comment by pron** [comment]
Sure. Thanks!
